const SWIPE_DISTANCE = 60;
const SWIPE_VELOCITY = 500;
const FLICK_MIN_DISTANCE = 20;
const SLIDE_DURATION = 0.28;
const FADE_DURATION = 0.2;
const PRELOAD_IDLE_TIMEOUT = 800;
const PRELOAD_FALLBACK_DELAY = 120;

export {
  SWIPE_DISTANCE,
  SWIPE_VELOCITY,
  FLICK_MIN_DISTANCE,
  SLIDE_DURATION,
  FADE_DURATION,
  PRELOAD_IDLE_TIMEOUT,
  PRELOAD_FALLBACK_DELAY,
};
