const SWIPE_DISTANCE = 60;
const SWIPE_VELOCITY = 500;
const FLICK_MIN_DISTANCE = 20;
const PRELOAD_IDLE_TIMEOUT = 800;
const PRELOAD_FALLBACK_DELAY = 120;

export {
  SWIPE_DISTANCE,
  SWIPE_VELOCITY,
  FLICK_MIN_DISTANCE,
  PRELOAD_IDLE_TIMEOUT,
  PRELOAD_FALLBACK_DELAY,
};
